# Lunaモデルの学習

### Lunaサイト
https://luna16.grand-challenge.org/Description/

### データセット概要
アーカイブを展開した状態のすべてのデータで約220GBを必要とする.  
+ annotations.csv
+ candidates.csv
+ sampleSubmission.csv
+ candidates_V2.zip
+ evaluationScript.zip
+ seg-lungs-LUNA16.zip
1. subset0.zip
2. subset1.zip
3. subset2.zip
4. subset3.zip
5. subset4.zip
6. subset5.zip
7. subset6.zip
8. subset7.zip
9. subset8.zip
10. subset10.zip

### subsetの中身
+ series_uidをユニークIDとして*.mhdと*.rawの2種類のファイルがある

In [1]:

import datetime
from p2_ct_project.util.logconf import logging
log = logging.getLogger('nb')
# log.setLevel(logging.WARN)
log.setLevel(logging.INFO)
log.setLevel(logging.DEBUG)

from p2_ct_project.util.util import importstr

# run_everything
def run(app, *argv):
    argv = list(argv)
    argv.insert(0, '--num-workers=8')
    # 4コア8スレッドのCPUを仮定
    log.info("Running: {}({!r}).main()".format(app, argv))
    print("*app.rsplit('.', 1) : ", *app.rsplit('.', 1))

    app_cls = importstr(*app.rsplit('.', 1)) # __import__を実行
    app_cls(argv).main()

    log.info("Finished: {}.({!r}).main()".format(app, argv))

In [2]:
import os
import shutil

# clean up any old data that might be around.
# We don't call this by default because it's destructive, 
# and would waste a lot of time if it ran when nothing 
# on the application side had changed.
tag_version = "unversioned"
cache_dir = f"F:/Luna16/cache/{tag_version}"
def cleanCache():
    shutil.rmtree(cache_dir)
    os.mkdir(cache_dir)

# cleanCache()

Fancacheのclose

In [2]:
from p2_ct_project.p2ch10.dataset_luna import raw_cache
raw_cache.close()

from p2_ct_project.p2ch12.mod_dataset_luna import raw_cache
raw_cache.close()

from p2_ct_project.p2ch13.balanced_dataset_luna_seg import raw_cache
raw_cache.close()

module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch10\..


OperationalError: database or disk is full

### 各チャプターで共通の学習設定

In [2]:
experiment_epochs = 2
training_epochs = 20
final_epochs = 50
seg_epochs = 10

# Chapter11

### デフォルト設定で学習

In [3]:
# run('p2_ct_project.p2ch11.prepcache_luna.LunaPrepCacheApp', '--datasetdir=E:/Luna16')

2023-05-14 19:29:53,424 INFO     pid:19988 nb:015:run Running: p2_ct_project.p2ch11.prepcache_luna.LunaPrepCacheApp(['--num-workers=8', '--datasetdir=E:/Luna16']).main()


*app.rsplit('.', 1) :  p2_ct_project.p2ch11.prepcache_luna LunaPrepCacheApp
module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..


c:\Users\InoueShinichi\anaconda3\envs\Py39WorkingEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..\p2ch10\..


2023-05-14 19:30:55,474 INFO     pid:19988 p2_ct_project.p2ch11.prepcache_luna:057:main Starting LunaPrepCacheApp, Namespace(batch_size=1024, num_workers=8, datasetdir='E:/Luna16')


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..\p2ch11\..
module:  <module 'p2_ct_project' (namespace)>


2023-05-14 19:30:59,295 INFO     pid:19988 p2ch10.dataset_luna:206:__init__ <p2ch10.dataset_luna.LunaDataset object at 0x0000015873D75B50>: 0 training samples
2023-05-14 19:30:59,304 WARNING  pid:19988 util.util:219:enumerateWithEstimate Stuffing cache ----/0, starting
2023-05-14 19:31:09,330 WARNING  pid:19988 util.util:249:enumerateWithEstimate Stuffing cache ----/0, done at 2023-05-14 19:31:09
2023-05-14 19:31:09,331 INFO     pid:19988 nb:021:run Finished: p2_ct_project.p2ch11.prepcache_luna.LunaPrepCacheApp.(['--num-workers=8', '--datasetdir=E:/Luna16']).main()


In [3]:
# run('p2_ct_project.p2ch11.training_luna.LunaTrainingApp', '--datasetdir=E:/Luna16', '--epochs=1')

2023-05-14 20:36:56,508 INFO     pid:15912 nb:015:run Running: p2_ct_project.p2ch11.training_luna.LunaTrainingApp(['--num-workers=8', '--datasetdir=E:/Luna16', '--epochs=1']).main()


*app.rsplit('.', 1) :  p2_ct_project.p2ch11.training_luna LunaTrainingApp
module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..


c:\Users\InoueShinichi\anaconda3\envs\Py39WorkingEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..\p2ch10\..


2023-05-14 20:36:58,532 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:093:initModel Using CUDA; 1 devices.
2023-05-14 20:36:58,608 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:154:main Starting LunaTrainingApp, Namespace(num_workers=8, batch_size=32, epochs=1, tb_prefix='p2ch11', comment='dwlpt', datasetdir='E:/Luna16')


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch11\..\p2ch11\..
module:  <module 'p2_ct_project' (namespace)>


2023-05-14 20:37:01,768 INFO     pid:15912 p2ch10.dataset_luna:206:__init__ <p2ch10.dataset_luna.LunaDataset object at 0x000001598AD92EB0>: 551065 training samples
2023-05-14 20:37:01,779 INFO     pid:15912 p2ch10.dataset_luna:206:__init__ <p2ch10.dataset_luna.LunaDataset object at 0x00000159928B1EB0>: 55107 validation samples
2023-05-14 20:37:01,780 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:161:main Epoch 1 of 1, 17221/1723 batches of size 32*1
2023-05-14 20:37:02,574 WARNING  pid:15912 util.util:219:enumerateWithEstimate E1 Training ----/17221, starting
2023-05-14 20:37:46,302 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Training  256/17221, done at 2023-05-14 20:59:16, 0:21:48
2023-05-14 20:40:10,042 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Training 2048/17221, done at 2023-05-14 21:00:19, 0:22:51
2023-05-14 21:00:03,387 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Training 16384/17221, done at 2023-05-14 21:01:12, 0:23:45
2023-

negHist_mask
 tensor([False, False, False,  ..., False, False, False])
negHist_mask.shape torch.Size([551065])
metrics_t[METRICS_PRED_NDX, negHist_mask]
 tensor([2.6185e+02, 2.4933e+02, 2.6980e+02, 1.9931e+02, 1.1570e+02, 1.7849e+02,
        1.1812e+02, 1.3153e+02, 1.1912e+02, 1.4036e+02, 5.8276e+01, 6.2885e+01,
        1.9820e+02, 1.3893e+02, 1.5186e+02, 6.5188e+01, 1.0087e+02, 4.1260e+01,
        1.5445e+02, 5.1070e+01, 3.9589e+01, 8.9356e+01, 6.1588e+01, 4.4534e+01,
        1.6192e+02, 1.5790e+00, 1.2916e+00, 1.0763e+00, 1.0785e+00, 1.4410e+00,
        1.2835e+00, 1.5326e+00, 1.5402e+00, 1.3848e+00, 1.4073e+00, 9.6501e-01,
        1.4509e+00, 1.4294e+00, 1.4985e+00, 1.4841e+00, 1.0428e+00, 1.4622e+00,
        1.0019e+00, 1.3761e+00, 6.7787e-01, 5.5590e-01, 5.0235e-01, 1.4668e+00,
        1.0142e+00, 1.1207e+00, 1.4636e+00, 1.5058e+00, 1.4441e+00, 1.4595e+00,
        1.2471e+00, 1.2683e+00, 1.4196e+00, 4.8129e-01, 1.0785e-01, 4.9486e-02,
        6.3805e-01, 1.3760e-01, 4.4769e-01, 3.

2023-05-14 21:01:34,943 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Validation    64/1723, done at 2023-05-14 21:03:02, 0:01:30
2023-05-14 21:01:42,764 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Validation   256/1723, done at 2023-05-14 21:02:46, 0:01:14
2023-05-14 21:02:12,336 INFO     pid:15912 util.util:236:enumerateWithEstimate E1 Validation  1024/1723, done at 2023-05-14 21:02:40, 0:01:08
2023-05-14 21:02:39,374 WARNING  pid:15912 util.util:249:enumerateWithEstimate E1 Validation  ----/1723, done at 2023-05-14 21:02:39
2023-05-14 21:02:39,375 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:281:logMetrics E1 LunaTrainingApp
2023-05-14 21:02:39,376 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:316:logMetrics E1 val      9718495.0000 loss, 100.0% correct, 1.0000 precision, 1.0000 recall, 1.0000 f1 score
2023-05-14 21:02:39,377 INFO     pid:15912 p2_ct_project.p2ch11.training_luna:330:logMetrics E1 val_neg  0.0000 loss, 100.0% correct (54971 

# Chapter12
+ 陽性サンプルと陰性サンプルの均一化

## 結節データをかさ増しする
+ LunaDatasetの結節候補データは, 結節でないデータと結節データの比率が均等でない

### 課題
+ ラベルが均等でないデータセットでは, 学習時にデータ比率が大きいラベル側にNNモデルが引っ張られ, 推論でデータ比率の大きなラベルばかりを推論結果として出力してしまう.

### 解決策
1. 学習時は, 各ラベルのデータ数を均等にする. 
2. 損失関数で, 比率の小さいラベルデータに対して更新勾配(誤差)を大きくする処理を追加する

#### 今回は比率の小さいラベルデータをかさ増しする

### 結節データ(比率の小さいラベルデータ)のかさ増しをする方法
1. PytorchのDataLoader関数の`sampler=...`オプションを使用する方法. <br> データセットの元々のイテレーション順序を上書きすることができ, <br> 特定のサンプルの抽出を制限したり, 逆に複数回抽出することが可能. これはデータセット自体をコントロールできない場合に非常に有効.
2. 直接データセットをコントロールできる場合, Datasetクラスのサブクラスの中で, 必要となるデータを再構成して, かさ増しする.

### データセット内でクラスバランスを調整する
+ LunaDataset内に追加の実装を行い, 訓練セットの陽性サンプル数と陰性サンプル数が1対1になるように変更する

In [3]:
run('p2_ct_project.p2ch12.prepcache_luna.LunaPrepCacheApp', '--datasetdir=E:/Luna16')

2023-05-26 01:29:18,400 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.prepcache_luna.LunaPrepCacheApp(['--num-workers=8', '--datasetdir=E:/Luna16']).main()


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.prepcache_luna LunaPrepCacheApp
module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..


c:\Users\InoueShinichi\anaconda3\envs\Py39WorkingEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..\p2ch12\..


2023-05-26 01:29:22,072 INFO     pid:21764 p2_ct_project.p2ch12.prepcache_luna:056:main Starting LunaPrepCacheApp, Namespace(batch_size=1024, num_workers=8, datasetdir='E:/Luna16')


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..\p2ch11\..
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 01:29:26,168 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265CF75CE80>: 551065 training samples, 549714 neg, 1351 pos, unbalanced ratio
2023-05-26 01:29:26,169 WARNING  pid:21764 util.util:226:enumerateWithEstimate Stuffing cache ----/539, starting
2023-05-26 01:32:22,116 INFO     pid:21764 util.util:243:enumerateWithEstimate Stuffing cache   64/539, done at 2023-05-26 01:50:11, 0:19:57
2023-05-26 01:39:25,304 INFO     pid:21764 util.util:243:enumerateWithEstimate Stuffing cache  256/539, done at 2023-05-26 01:49:50, 0:19:36
2023-05-26 01:49:27,346 WARNING  pid:21764 util.util:256:enumerateWithEstimate Stuffing cache ----/539, done at 2023-05-26 01:49:27
2023-05-26 01:49:27,438 INFO     pid:21764 nb:021:run Finished: p2_ct_project.p2ch12.prepcache_luna.LunaPrepCacheApp.(['--num-workers=8', '--datasetdir=E:/Luna16']).main()


In [ ]:
# run('p2_ct_project.p2ch12.mod_training_luna.LunatrainingApp', '--datasetdir=E:/Luna16', '--epochs=1', 'unbalanced')

In [4]:
# データサンプルの調整
# run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', '--datasetdir=E:/Luna16', f'--epochs=1', '--balanced', 'balanced')

2023-05-15 10:55:37,515 INFO     pid:20108 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--datasetdir=E:/Luna16', '--epochs=1', '--balanced', 'balanced']).main()


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..


c:\Users\InoueShinichi\anaconda3\envs\Py39WorkingEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..\p2ch12\..


2023-05-15 10:55:39,401 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-15 10:55:39,488 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=1, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=False, augment_scale=False, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='balanced')


module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..\p2ch11\..
module:  <module 'p2_ct_project' (namespace)>


2023-05-15 10:55:43,648 INFO     pid:20108 p2ch12.mod_dataset_luna:330:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000238C23E7B50>: 551065 training samples, 549714 neg, 1351 pos, 1:1 ratio
2023-05-15 10:55:43,682 INFO     pid:20108 p2ch12.mod_dataset_luna:330:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000238CCA15D30>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-15 10:55:43,683 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 1, train: 6250 / validation: 1723 batches of size 32*1
2023-05-15 10:55:44,717 WARNING  pid:20108 util.util:219:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-15 10:56:16,366 INFO     pid:20108 util.util:236:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-15 11:03:46, 0:07:34
2023-05-15 10:56:32,509 INFO     pid:20108 util.util:236:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-15 11:04:40, 0:08:28
2023-05-15 10:57:37,955 INFO     pid:2

sum(metrics_[METRICS_PRED_NDX] > 0.01) : 陽性尤度が>0.01な推論サンプル数 tensor(152531)
negHist_mask
 tensor([False,  True, False,  ...,  True, False,  True])
negHist_mask.shape torch.Size([200000])
metrics_t[METRICS_PRED_NDX, negHist_mask]
 tensor([0.2845, 0.0391, 0.0908,  ..., 0.1316, 0.0312, 0.2134])
metrics_t[METRICS_PRED_NDX, negHist_mask].shape torch.Size([97515])
sum(metrics_[METRICS_PRED_NDX] < 0.99) : 陽性尤度が<0.99な推論サンプル数 tensor(181818)
posHist_mask
 tensor([False, False,  True,  ..., False,  True, False])
posHist_mask.shape torch.Size([200000])
metrics_t[METRICS_PRED_NDX, posHist_mask]
 tensor([3.1107e-02, 4.9949e-01, 9.5218e-01,  ..., 9.8525e-02, 3.5510e-03,
        3.0875e-05])
metrics_t[METRICS_PRED_NDX, posHist_mask].shape torch.Size([87338])


2023-05-15 11:05:20,007 INFO     pid:20108 util.util:236:enumerateWithEstimate E1 Validation    64/1723, done at 2023-05-15 11:06:33, 0:01:16
2023-05-15 11:05:27,407 INFO     pid:20108 util.util:236:enumerateWithEstimate E1 Validation   256/1723, done at 2023-05-15 11:06:25, 0:01:08
2023-05-15 11:05:57,712 INFO     pid:20108 util.util:236:enumerateWithEstimate E1 Validation  1024/1723, done at 2023-05-15 11:06:25, 0:01:07
2023-05-15 11:06:27,498 WARNING  pid:20108 util.util:249:enumerateWithEstimate E1 Validation  ----/1723, done at 2023-05-15 11:06:27
2023-05-15 11:06:27,499 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:365:logMetrics E1 LunaTrainingApp
2023-05-15 11:06:27,501 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:400:logMetrics E1 val      0.1916 loss,  93.7% correct, 0.0077 precision, 0.1912 recall, 0.0148 f1 score
2023-05-15 11:06:27,501 INFO     pid:20108 p2_ct_project.p2ch12.mod_training_luna:414:logMetrics E1 val_neg  0.1913 loss,  93.9% correct (

sum(metrics_[METRICS_PRED_NDX] > 0.01) : 陽性尤度が>0.01な推論サンプル数 tensor(53783)
negHist_mask
 tensor([True, True, True,  ..., True, True, True])
negHist_mask.shape torch.Size([55107])
metrics_t[METRICS_PRED_NDX, negHist_mask]
 tensor([0.0796, 0.0551, 0.1933,  ..., 0.4828, 0.0795, 0.0924])
metrics_t[METRICS_PRED_NDX, negHist_mask].shape torch.Size([53708])
sum(metrics_[METRICS_PRED_NDX] < 0.99) : 陽性尤度が<0.99な推論サンプル数 tensor(53607)
posHist_mask
 tensor([False, False, False,  ..., False, False, False])
posHist_mask.shape torch.Size([55107])
metrics_t[METRICS_PRED_NDX, posHist_mask]
 tensor([1.1657e-01, 4.4717e-02, 3.6934e-01, 1.3351e-05, 2.3842e-07, 1.7775e-02,
        8.8635e-01, 2.6147e-03, 3.2305e-05, 7.2548e-04, 1.3078e-01, 3.0012e-04,
        -0.0000e+00, 6.7700e-04, 1.2537e-03, 2.2325e-04, 2.0772e-03, 2.0342e-01,
        3.1510e-01, 7.7357e-01, 1.1206e-05, 5.8096e-02, 3.9944e-02, 1.7780e-02,
        4.8004e-01, 6.2137e-01, 1.0729e-06, 1.7881e-05, 6.6540e-01, 5.7934e-05,
        1.8002e-03, 

In [8]:
# import numpy as np
# a = np.empty((1, 100), dtype=np.float32) > 0.5
# print(a)
# ans = np.sum(a)
# print(ans)

[[False False False False False False  True False False False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False  True False  True False  True False  True False
   True False  True False]]
46


### データ拡張の結果を比較する

In [4]:
# データサンプルの調整
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', '--datasetdir=E:/Luna16', f'--epochs={training_epochs}', '--balanced', 'balanced')

2023-05-26 01:50:40,472 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--datasetdir=E:/Luna16', '--epochs=20', '--balanced', 'balanced']).main()


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module_parent_dir c:\Users\InoueShinichi\Desktop\MyGithub\Book_HowToPytorch\p2_ct_project\p2ch12\..


2023-05-26 01:50:41,333 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 01:50:41,491 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=False, augment_scale=False, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='balanced')


module:  <module 'p2_ct_project' (namespace)>


2023-05-26 01:50:41,852 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265CF85F3A0>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 01:50:41,891 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265D9FB2850>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 01:50:41,892 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 01:50:44,783 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 01:51:18,862 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 01:59:18, 0:08:03
2023-05-26 01:51:35,565 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 02:00:03, 0:08:49
2023-05-26 01:52:43,132 INFO     pid:

In [5]:
# データ拡張　フリップ
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augment-flip', 'flip')

2023-05-26 05:11:07,365 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augment-flip', 'flip']).main()
2023-05-26 05:11:07,370 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 05:11:07,372 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=True, augment_offset=False, augment_scale=False, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='flip')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 05:11:07,723 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265CF85FAF0>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 05:11:07,764 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F45F40>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 05:11:07,765 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 05:11:07,959 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 05:11:36,278 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 05:19:16, 0:07:44
2023-05-26 05:11:51,832 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 05:19:48, 0:08:16
2023-05-26 05:12:54,381 INFO     pid:

In [6]:
# データ拡張 平行移動
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augment-offset', 'offset')

2023-05-26 08:28:52,029 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augment-offset', 'offset']).main()
2023-05-26 08:28:52,035 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 08:28:52,038 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=True, augment_scale=False, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='offset')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 08:28:52,404 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F45FD0>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 08:28:52,439 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F46FA0>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 08:28:52,440 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 08:28:52,613 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 08:29:20,802 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 08:37:00, 0:07:44
2023-05-26 08:29:36,245 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 08:37:29, 0:08:13
2023-05-26 08:30:38,497 INFO     pid:

In [7]:
# データ拡張 スケール
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augment-scale', 'scale')

2023-05-26 11:45:34,983 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augment-scale', 'scale']).main()
2023-05-26 11:45:34,987 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 11:45:34,989 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=False, augment_scale=True, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='scale')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 11:45:35,334 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265D9A2A700>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 11:45:35,368 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F46C70>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 11:45:35,369 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 11:45:35,545 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 11:46:03,610 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 11:53:40, 0:07:41
2023-05-26 11:46:19,030 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 11:54:11, 0:08:12
2023-05-26 11:47:21,416 INFO     pid:

In [8]:
# データ拡張　回転
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augment-rotate', 'rotate')

2023-05-26 15:03:32,984 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augment-rotate', 'rotate']).main()
2023-05-26 15:03:32,990 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 15:03:32,992 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=False, augment_scale=False, augment_rotate=True, augment_noise=False, datasetdir='E:/Luna16', comment='rotate')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 15:03:33,386 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F45310>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 15:03:33,422 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E2000AC0>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 15:03:33,422 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 15:03:33,608 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 15:04:01,794 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 15:11:28, 0:07:31
2023-05-26 15:04:17,275 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 15:12:09, 0:08:11
2023-05-26 15:05:19,443 INFO     pid:

In [9]:
# データ拡張　ノイズ付加
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augment-noise', 'noise')

2023-05-26 18:20:43,183 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augment-noise', 'noise']).main()
2023-05-26 18:20:43,188 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 18:20:43,190 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=False, augment_flip=False, augment_offset=False, augment_scale=False, augment_rotate=False, augment_noise=True, datasetdir='E:/Luna16', comment='noise')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 18:20:43,547 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265E8F45FD0>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 18:20:43,586 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265D9FB2820>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 18:20:43,587 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 18:20:43,776 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 18:21:12,227 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 18:28:49, 0:07:41
2023-05-26 18:21:27,765 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 18:29:23, 0:08:15
2023-05-26 18:22:30,258 INFO     pid:

In [10]:
# データ拡張　フリップ, 平行移動, スケール, 回転, ノイズ付加
run('p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp', f'--epochs={training_epochs}', '--balanced', '--augmented', 'fully-augmented')

2023-05-26 21:38:47,045 INFO     pid:21764 nb:015:run Running: p2_ct_project.p2ch12.mod_training_luna.LunaTrainingApp(['--num-workers=8', '--epochs=20', '--balanced', '--augmented', 'fully-augmented']).main()
2023-05-26 21:38:47,051 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:156:initModel Using CUDA; 1 devices.
2023-05-26 21:38:47,053 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:225:main Starting LunaTrainingApp, Namespace(batch_size=32, num_workers=8, epochs=20, tb_prefix='p2ch12', balanced=True, augmented=True, augment_flip=False, augment_offset=False, augment_scale=False, augment_rotate=False, augment_noise=False, datasetdir='E:/Luna16', comment='fully-augmented')


*app.rsplit('.', 1) :  p2_ct_project.p2ch12.mod_training_luna LunaTrainingApp
module:  <module 'p2_ct_project' (namespace)>


2023-05-26 21:38:47,384 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265CF8659D0>: 495958 training samples, 494743 neg, 1215 pos, 1:1 ratio
2023-05-26 21:38:47,426 INFO     pid:21764 p2ch12.mod_dataset_luna:380:__init__ <p2ch12.mod_dataset_luna.LunaDataset object at 0x00000265D9FB2AC0>: 55107 validation samples, 54971 neg, 136 pos, unbalanced ratio
2023-05-26 21:38:47,427 INFO     pid:21764 p2_ct_project.p2ch12.mod_training_luna:233:main Epoch 1 of 20, train: 6250 / validation: 1723 batches of size 32*1
2023-05-26 21:38:47,621 WARNING  pid:21764 util.util:226:enumerateWithEstimate E1 Training ----/6250, starting
2023-05-26 21:39:16,181 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training   64/6250, done at 2023-05-26 21:46:57, 0:07:46
2023-05-26 21:39:31,640 INFO     pid:21764 util.util:243:enumerateWithEstimate E1 Training  256/6250, done at 2023-05-26 21:47:26, 0:08:14
2023-05-26 21:40:34,024 INFO     pid: